services:
  server:
    build:
      context: "."
      dockerfile: Dockerfile
    command:
      - top
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#      - "8002:8002"
#      - "8003:8003"
#      - "3456:3456"
#      - "3457:3457"
    networks:
      - "backend"
    volumes:
      - "${DATA_DIR:-./opt}/server:/opt/kds-sms-server"
    environment:
      KDS_SMS_SERVER_SETTINGS_FILE: "/opt/kds-sms-server/settings.json"
  db:
    image: "mariadb:${DB_VERSION:-latest}"
    restart: 'always'
    ports:
      - "3306:3306"
    networks:
      - "backend"
    volumes:
      - "${DATA_DIR:-./opt}/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-xxx}"
      MYSQL_DATABASE: "${DB_DATABASE:-kds-sms-server}"
      MYSQL_USER: "${DB_USER:-kds-sms-server}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-xxx}"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  backend:

